package com.stirlang.codegen;

import com.stirlang.ast.*;
import com.stirlang.lexer.TokenType;
import com.stirlang.semantic.DataType;

import java.util.List;

/**
 * Translates a validated Stirlang AST into clean, readable, and properly indented Java source code.
 */
public class JavaCodeGenerator {
    private final ProgramNode program;
    private final String className;
    private final StringBuilder out = new StringBuilder();
    private int indentLevel = 0;
    private int loopVarCounter = 0;

    public JavaCodeGenerator(ProgramNode program, String className) {
        this.program = program;
        this.className = className != null && !className.isEmpty() ? className : "GeneratedProgram";
    }

    public JavaCodeGenerator(ProgramNode program) {
        this(program, "GeneratedProgram");
    }

    /**
     * Generates the complete Java source code for the program.
     */
    public String generate() {
        out.setLength(0);
        indentLevel = 0;
        loopVarCounter = 0;

        appendLine("// Generated by Stirlang Compiler");
        appendLine("import java.util.Objects;");
        appendLine("import java.util.ArrayList;");
        appendLine("import java.util.List;");
        appendLine();
        appendLine("public class " + className + " {");
        indentLevel++;

        List<FunctionNode> functions = program.getFunctions();
        for (int i = 0; i < functions.size(); i++) {
            FunctionNode fn = functions.get(i);
            generateFunction(fn);
            if (i < functions.size() - 1) {
                appendLine();
            }
        }

        appendLine();
        appendRuntimeHelpers();

        indentLevel--;
        appendLine("}");
        return out.toString();
    }

    private void generateFunction(FunctionNode fn) {
        if (fn.isMain()) {
            appendLine("public static void main(String[] args) {");
            indentLevel++;
            appendLine("try {");
            indentLevel++;
            generateBlock(fn.getBody());
            indentLevel--;
            appendLine("} catch (StirlangRuntimeError e) {");
            indentLevel++;
            appendLine("System.err.println(\"Stirlang Runtime Error: \" + e.getMessage());");
            appendLine("System.exit(1);");
            indentLevel--;
            appendLine("}");
            indentLevel--;
            appendLine("}");
        } else {
            String returnType = fn.getReturnType().getJavaTypeName();
            StringBuilder params = new StringBuilder();
            for (int i = 0; i < fn.getParameters().size(); i++) {
                String p = fn.getParameters().get(i);
                DataType pType = fn.getParameterTypes().getOrDefault(p, DataType.ANY);
                if (i > 0) params.append(", ");
                params.append(pType.getJavaTypeName()).append(" ").append(p);
            }
            appendLine("public static " + returnType + " " + fn.getName() + "(" + params + ") {");
            indentLevel++;
            generateBlock(fn.getBody());
            indentLevel--;
            appendLine("}");
        }
    }

    private void generateBlock(BlockNode block) {
        for (StatementNode stmt : block.getStatements()) {
            generateStatement(stmt);
        }
    }

    private void generateStatement(StatementNode stmt) {
        if (stmt instanceof AssignmentStatementNode) {
            generateAssignment((AssignmentStatementNode) stmt);
        } else if (stmt instanceof IndexAssignmentStatementNode) {
            generateIndexAssignment((IndexAssignmentStatementNode) stmt);
        } else if (stmt instanceof PrintStatementNode) {
            generatePrint((PrintStatementNode) stmt);
        } else if (stmt instanceof IfStatementNode) {
            generateIf((IfStatementNode) stmt);
        } else if (stmt instanceof LoopStatementNode) {
            generateLoop((LoopStatementNode) stmt);
        } else if (stmt instanceof BreakStatementNode) {
            appendLine("break;");
        } else if (stmt instanceof ContinueStatementNode) {
            appendLine("continue;");
        } else if (stmt instanceof ReturnStatementNode) {
            generateReturn((ReturnStatementNode) stmt);
        } else if (stmt instanceof ExpressionStatementNode) {
            appendLine(generateExpression(((ExpressionStatementNode) stmt).getExpression()) + ";");
        }
    }

    private void generateIndexAssignment(IndexAssignmentStatementNode assign) {
        IndexAccessExpressionNode target = assign.getTarget();
        String targetExpr = generateExpression(target.getTarget());
        String indexExpr = generateExpression(target.getIndex());
        if (target.getIndex().getEvaluatedType() == DataType.ANY) {
            indexExpr = "((Number) " + indexExpr + ").intValue()";
        }
        String valExpr = generateExpression(assign.getValue());
        appendLine("((StirlangArray) (" + targetExpr + ")).set(" + indexExpr + ", " + valExpr + ");");
    }

    private void generateLoop(LoopStatementNode loopStmt) {
        if (loopStmt.isInfinite()) {
            appendLine("while (true) {");
        } else if (loopStmt.hasExposedCounter()) {
            String var = loopStmt.getCounterVariable();
            String count = generateLoopCount(loopStmt.getCountExpression());
            appendLine("for (int " + var + " = 0; " + var + " < " + count + "; " + var + "++) {");
        } else {
            String var = "__loop" + (loopVarCounter++);
            String count = generateLoopCount(loopStmt.getCountExpression());
            appendLine("for (int " + var + " = 0; " + var + " < " + count + "; " + var + "++) {");
        }

        indentLevel++;
        generateBlock(loopStmt.getBody());
        indentLevel--;
        appendLine("}");
    }

    private String generateLoopCount(ExpressionNode expr) {
        String countStr = generateExpression(expr);
        if (expr != null && expr.getEvaluatedType() == DataType.ANY) {
            return "((Number) " + countStr + ").intValue()";
        }
        return countStr;
    }

    private void generateAssignment(AssignmentStatementNode assign) {
        String varName = assign.getVariableName();
        String expr = generateExpression(assign.getValue());

        if (assign.isDeclaration()) {
            String typeName = assign.getVariableType().getJavaTypeName();
            appendLine(typeName + " " + varName + " = " + expr + ";");
        } else {
            String op = assign.getOperator().getRepresentation();
            appendLine(varName + " " + op + " " + expr + ";");
        }
    }

    private void generatePrint(PrintStatementNode printStmt) {
        String expr = generateExpression(printStmt.getExpression());
        appendLine("System.out.println(" + expr + ");");
    }

    private void generateIf(IfStatementNode ifStmt) {
        String condition = generateExpression(ifStmt.getCondition());
        appendLine("if (" + condition + ") {");
        indentLevel++;
        generateBlock(ifStmt.getThenBranch());
        indentLevel--;

        for (IfStatementNode.ElseIfBranch branch : ifStmt.getElseIfBranches()) {
            String elseIfCondition = generateExpression(branch.getCondition());
            appendLine("} else if (" + elseIfCondition + ") {");
            indentLevel++;
            generateBlock(branch.getBody());
            indentLevel--;
        }

        if (ifStmt.getElseBranch() != null) {
            appendLine("} else {");
            indentLevel++;
            generateBlock(ifStmt.getElseBranch());
            indentLevel--;
        }

        appendLine("}");
    }

    private void generateReturn(ReturnStatementNode returnStmt) {
        if (returnStmt.getValue() != null) {
            appendLine("return " + generateExpression(returnStmt.getValue()) + ";");
        } else {
            appendLine("return;");
        }
    }

    private String generateExpression(ExpressionNode expr) {
        if (expr instanceof LiteralExpressionNode) {
            LiteralExpressionNode lit = (LiteralExpressionNode) expr;
            if (lit.getEvaluatedType() == DataType.STRING) {
                return escapeJavaString(lit.getValue().toString());
            }
            return String.valueOf(lit.getValue());
        }

        if (expr instanceof VariableExpressionNode) {
            return ((VariableExpressionNode) expr).getName();
        }

        if (expr instanceof ArrayLiteralNode) {
            ArrayLiteralNode arr = (ArrayLiteralNode) expr;
            if (arr.getElements().isEmpty()) {
                return "new StirlangArray()";
            }
            StringBuilder sb = new StringBuilder("StirlangArray.of(");
            for (int i = 0; i < arr.getElements().size(); i++) {
                if (i > 0) sb.append(", ");
                sb.append(generateExpression(arr.getElements().get(i)));
            }
            sb.append(")");
            return sb.toString();
        }

        if (expr instanceof IndexAccessExpressionNode) {
            IndexAccessExpressionNode idx = (IndexAccessExpressionNode) expr;
            String target = generateExpression(idx.getTarget());
            String index = generateExpression(idx.getIndex());
            if (idx.getIndex().getEvaluatedType() == DataType.ANY) {
                index = "((Number) " + index + ").intValue()";
            }
            DataType type = idx.getEvaluatedType();
            if (type == DataType.INT) {
                return "((StirlangArray) (" + target + ")).getInt(" + index + ")";
            } else if (type == DataType.DECIMAL) {
                return "((StirlangArray) (" + target + ")).getDouble(" + index + ")";
            } else if (type == DataType.STRING) {
                return "((StirlangArray) (" + target + ")).getString(" + index + ")";
            } else if (type == DataType.BOOLEAN) {
                return "((StirlangArray) (" + target + ")).getBoolean(" + index + ")";
            } else if (type == DataType.ARRAY) {
                return "((StirlangArray) (" + target + ")).getArray(" + index + ")";
            } else {
                return "((StirlangArray) (" + target + ")).get(" + index + ")";
            }
        }

        if (expr instanceof MethodCallExpressionNode) {
            MethodCallExpressionNode call = (MethodCallExpressionNode) expr;
            String target = generateExpression(call.getTarget());
            String method = call.getMethodName();
            StringBuilder sb = new StringBuilder();
            sb.append("((StirlangArray) (").append(target).append(")).").append(method).append("(");
            for (int i = 0; i < call.getArguments().size(); i++) {
                if (i > 0) sb.append(", ");
                ExpressionNode arg = call.getArguments().get(i);
                String argStr = generateExpression(arg);
                if ((method.equals("removeIndex") || (method.equals("add") && i == 1)) && arg.getEvaluatedType() == DataType.ANY) {
                    argStr = "((Number) " + argStr + ").intValue()";
                }
                sb.append(argStr);
            }
            sb.append(")");
            return sb.toString();
        }

        if (expr instanceof UnaryExpressionNode) {
            UnaryExpressionNode unary = (UnaryExpressionNode) expr;
            String op = unary.getOperator() == TokenType.NOT ? "!" : "-";
            return op + "(" + generateExpression(unary.getOperand()) + ")";
        }

        if (expr instanceof BinaryExpressionNode) {
            BinaryExpressionNode bin = (BinaryExpressionNode) expr;
            String left = generateExpression(bin.getLeft());
            String right = generateExpression(bin.getRight());
            TokenType op = bin.getOperator();

            boolean isObjectComp = (bin.getLeft().getEvaluatedType() == DataType.STRING ||
                                    bin.getRight().getEvaluatedType() == DataType.STRING ||
                                    bin.getLeft().getEvaluatedType() == DataType.ARRAY ||
                                    bin.getRight().getEvaluatedType() == DataType.ARRAY ||
                                    bin.getLeft().getEvaluatedType() == DataType.ANY ||
                                    bin.getRight().getEvaluatedType() == DataType.ANY);

            if (op == TokenType.EQUAL) {
                if (isObjectComp) {
                    return "Objects.equals(" + left + ", " + right + ")";
                }
                return "(" + left + " == " + right + ")";
            }

            if (op == TokenType.NOT_EQUAL) {
                if (isObjectComp) {
                    return "!Objects.equals(" + left + ", " + right + ")";
                }
                return "(" + left + " != " + right + ")";
            }

            if (op == TokenType.AND) {
                return "(" + left + " && " + right + ")";
            }

            if (op == TokenType.OR) {
                return "(" + left + " || " + right + ")";
            }

            return "(" + left + " " + op.getRepresentation() + " " + right + ")";
        }

        if (expr instanceof FunctionCallExpressionNode) {
            FunctionCallExpressionNode call = (FunctionCallExpressionNode) expr;
            StringBuilder sb = new StringBuilder();
            sb.append(call.getFunctionName()).append("(");
            for (int i = 0; i < call.getArguments().size(); i++) {
                if (i > 0) sb.append(", ");
                sb.append(generateExpression(call.getArguments().get(i)));
            }
            sb.append(")");
            return sb.toString();
        }

        return "";
    }

    private String escapeJavaString(String text) {
        StringBuilder sb = new StringBuilder("\"");
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            switch (c) {
                case '"':
                    sb.append("\\\"");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                default:
                    sb.append(c);
                    break;
            }
        }
        sb.append("\"");
        return sb.toString();
    }

    private void appendRuntimeHelpers() {
        appendLine("// --- Stirlang Runtime Helpers ---");
        appendLine("public static class StirlangRuntimeError extends RuntimeException {");
        indentLevel++;
        appendLine("public StirlangRuntimeError(String message) {");
        indentLevel++;
        appendLine("super(message);");
        indentLevel--;
        appendLine("}");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public static class StirlangArray {");
        indentLevel++;
        appendLine("private final List<Object> elements = new ArrayList<>();");
        appendLine("private String elementType = null;");
        appendLine();
        appendLine("public StirlangArray() {}");
        appendLine();
        appendLine("public static StirlangArray of(Object... items) {");
        indentLevel++;
        appendLine("StirlangArray arr = new StirlangArray();");
        appendLine("for (Object item : items) {");
        indentLevel++;
        appendLine("arr.addToEnd(item);");
        indentLevel--;
        appendLine("}");
        appendLine("return arr;");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public String getElementType() { return elementType; }");
        appendLine("public void setElementType(String elementType) { this.elementType = elementType; }");
        appendLine("public int size() { return elements.size(); }");
        appendLine("public boolean isEmpty() { return elements.isEmpty(); }");
        appendLine();
        appendLine("public static String typeOf(Object value) {");
        indentLevel++;
        appendLine("if (value == null) return \"null\";");
        appendLine("if (value instanceof Integer || value instanceof Long || value instanceof Short || value instanceof Byte) return \"INT\";");
        appendLine("if (value instanceof Double || value instanceof Float) return \"DECIMAL\";");
        appendLine("if (value instanceof String) return \"STRING\";");
        appendLine("if (value instanceof Boolean) return \"BOOLEAN\";");
        appendLine("if (value instanceof StirlangArray) {");
        indentLevel++;
        appendLine("StirlangArray arr = (StirlangArray) value;");
        appendLine("if (arr.getElementType() == null) return \"ARRAY\";");
        appendLine("return \"ARRAY<\" + arr.getElementType() + \">\";");
        indentLevel--;
        appendLine("}");
        appendLine("return value.getClass().getSimpleName();");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public static boolean isCompatible(String expected, String actual) {");
        indentLevel++;
        appendLine("if (expected == null) return true;");
        appendLine("if (expected.equals(actual)) return true;");
        appendLine("if (expected.startsWith(\"ARRAY<\") && actual.equals(\"ARRAY\")) return true;");
        appendLine("if (expected.equals(\"ARRAY\") && actual.startsWith(\"ARRAY<\")) return true;");
        appendLine("if (expected.startsWith(\"ARRAY<\") && actual.startsWith(\"ARRAY<\")) {");
        indentLevel++;
        appendLine("String innerExpected = expected.substring(6, expected.length() - 1);");
        appendLine("String innerActual = actual.substring(6, actual.length() - 1);");
        appendLine("return isCompatible(innerExpected, innerActual);");
        indentLevel--;
        appendLine("}");
        appendLine("return false;");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("private void checkTypeForAdd(Object value) {");
        indentLevel++;
        appendLine("String valType = typeOf(value);");
        appendLine("if (elementType == null) {");
        indentLevel++;
        appendLine("elementType = valType;");
        indentLevel--;
        appendLine("} else {");
        indentLevel++;
        appendLine("if (!isCompatible(elementType, valType)) {");
        indentLevel++;
        appendLine("throw new StirlangRuntimeError(\"Type mismatch: cannot add value of type \" + valType + \" to array of type \" + elementType);");
        indentLevel--;
        appendLine("}");
        appendLine("if (value instanceof StirlangArray && elementType.startsWith(\"ARRAY<\")) {");
        indentLevel++;
        appendLine("StirlangArray subArr = (StirlangArray) value;");
        appendLine("if (subArr.getElementType() == null) {");
        indentLevel++;
        appendLine("subArr.setElementType(elementType.substring(6, elementType.length() - 1));");
        indentLevel--;
        appendLine("}");
        indentLevel--;
        appendLine("}");
        indentLevel--;
        appendLine("}");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public void addToEnd(Object value) {");
        indentLevel++;
        appendLine("checkTypeForAdd(value);");
        appendLine("elements.add(value);");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public void addToFront(Object value) {");
        indentLevel++;
        appendLine("checkTypeForAdd(value);");
        appendLine("elements.add(0, value);");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public void add(Object value, int index) {");
        indentLevel++;
        appendLine("checkTypeForAdd(value);");
        appendLine("int actual = index < 0 ? elements.size() + index : index;");
        appendLine("if (actual < 0 || actual > elements.size()) {");
        indentLevel++;
        appendLine("throw new StirlangRuntimeError(\"Array index out of range: \" + index + \" (size: \" + elements.size() + \")\");");
        indentLevel--;
        appendLine("}");
        appendLine("elements.add(actual, value);");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public Object get(int index) {");
        indentLevel++;
        appendLine("int actual = index < 0 ? elements.size() + index : index;");
        appendLine("if (actual < 0 || actual >= elements.size()) {");
        indentLevel++;
        appendLine("throw new StirlangRuntimeError(\"Array index out of range: \" + index + \" (size: \" + elements.size() + \")\");");
        indentLevel--;
        appendLine("}");
        appendLine("return elements.get(actual);");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public void set(int index, Object value) {");
        indentLevel++;
        appendLine("int actual = index < 0 ? elements.size() + index : index;");
        appendLine("if (actual < 0 || actual >= elements.size()) {");
        indentLevel++;
        appendLine("throw new StirlangRuntimeError(\"Array index out of range: \" + index + \" (size: \" + elements.size() + \")\");");
        indentLevel--;
        appendLine("}");
        appendLine("String valType = typeOf(value);");
        appendLine("if (elementType != null && !isCompatible(elementType, valType)) {");
        indentLevel++;
        appendLine("throw new StirlangRuntimeError(\"Type mismatch: cannot assign value of type \" + valType + \" to array of type \" + elementType);");
        indentLevel--;
        appendLine("}");
        appendLine("elements.set(actual, value);");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public void remove(Object value) {");
        indentLevel++;
        appendLine("String valType = typeOf(value);");
        appendLine("if (elementType != null && !isCompatible(elementType, valType)) {");
        indentLevel++;
        appendLine("throw new StirlangRuntimeError(\"Type mismatch: cannot remove value of type \" + valType + \" from array of type \" + elementType);");
        indentLevel--;
        appendLine("}");
        appendLine("elements.removeIf(e -> Objects.equals(e, value));");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public void removeIndex(int index) {");
        indentLevel++;
        appendLine("int actual = index < 0 ? elements.size() + index : index;");
        appendLine("if (actual < 0 || actual >= elements.size()) {");
        indentLevel++;
        appendLine("throw new StirlangRuntimeError(\"Array index out of range: \" + index + \" (size: \" + elements.size() + \")\");");
        indentLevel--;
        appendLine("}");
        appendLine("elements.remove(actual);");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public int getInt(int index) {");
        indentLevel++;
        appendLine("Object val = get(index);");
        appendLine("if (val instanceof Number) return ((Number) val).intValue();");
        appendLine("throw new StirlangRuntimeError(\"Expected integer element at index \" + index + \", found \" + typeOf(val));");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public double getDouble(int index) {");
        indentLevel++;
        appendLine("Object val = get(index);");
        appendLine("if (val instanceof Number) return ((Number) val).doubleValue();");
        appendLine("throw new StirlangRuntimeError(\"Expected decimal element at index \" + index + \", found \" + typeOf(val));");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public String getString(int index) {");
        indentLevel++;
        appendLine("Object val = get(index);");
        appendLine("if (val instanceof String) return (String) val;");
        appendLine("throw new StirlangRuntimeError(\"Expected string element at index \" + index + \", found \" + typeOf(val));");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public boolean getBoolean(int index) {");
        indentLevel++;
        appendLine("Object val = get(index);");
        appendLine("if (val instanceof Boolean) return (Boolean) val;");
        appendLine("throw new StirlangRuntimeError(\"Expected boolean element at index \" + index + \", found \" + typeOf(val));");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("public StirlangArray getArray(int index) {");
        indentLevel++;
        appendLine("Object val = get(index);");
        appendLine("if (val instanceof StirlangArray) return (StirlangArray) val;");
        appendLine("throw new StirlangRuntimeError(\"Expected array element at index \" + index + \", found \" + typeOf(val));");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("@Override");
        appendLine("public String toString() {");
        indentLevel++;
        appendLine("StringBuilder sb = new StringBuilder(\"{\");");
        appendLine("for (int i = 0; i < elements.size(); i++) {");
        indentLevel++;
        appendLine("if (i > 0) sb.append(\", \");");
        appendLine("Object elem = elements.get(i);");
        appendLine("if (elem instanceof String) {");
        indentLevel++;
        appendLine("sb.append(\"\\\"\").append(elem).append(\"\\\"\");");
        indentLevel--;
        appendLine("} else {");
        indentLevel++;
        appendLine("sb.append(elem);");
        indentLevel--;
        appendLine("}");
        indentLevel--;
        appendLine("}");
        appendLine("sb.append(\"}\");");
        appendLine("return sb.toString();");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("@Override");
        appendLine("public boolean equals(Object o) {");
        indentLevel++;
        appendLine("if (this == o) return true;");
        appendLine("if (!(o instanceof StirlangArray)) return false;");
        appendLine("StirlangArray that = (StirlangArray) o;");
        appendLine("return Objects.equals(elements, that.elements);");
        indentLevel--;
        appendLine("}");
        appendLine();
        appendLine("@Override");
        appendLine("public int hashCode() {");
        indentLevel++;
        appendLine("return Objects.hash(elements);");
        indentLevel--;
        appendLine("}");
        indentLevel--;
        appendLine("}");
    }

    private void appendLine(String line) {
        for (int i = 0; i < indentLevel; i++) {
            out.append("    ");
        }
        out.append(line).append("\n");
    }

    private void appendLine() {
        out.append("\n");
    }
}
