package com.stirlang.codegen;

import com.stirlang.ast.*;
import com.stirlang.lexer.TokenType;
import com.stirlang.semantic.DataType;

import java.util.List;

/**
 * Translates a validated Stirlang AST into clean, readable, and properly indented Java source code.
 */
public class JavaCodeGenerator {
    private final ProgramNode program;
    private final String className;
    private final StringBuilder out = new StringBuilder();
    private int indentLevel = 0;
    private int loopVarCounter = 0;

    public JavaCodeGenerator(ProgramNode program, String className) {
        this.program = program;
        this.className = className != null && !className.isEmpty() ? className : "GeneratedProgram";
    }

    public JavaCodeGenerator(ProgramNode program) {
        this(program, "GeneratedProgram");
    }

    /**
     * Generates the complete Java source code for the program.
     */
    public String generate() {
        out.setLength(0);
        indentLevel = 0;
        loopVarCounter = 0;

        appendLine("// Generated by Stirlang Compiler");
        appendLine("import java.util.Objects;");
        appendLine();
        appendLine("public class " + className + " {");
        indentLevel++;

        List<FunctionNode> functions = program.getFunctions();
        for (int i = 0; i < functions.size(); i++) {
            FunctionNode fn = functions.get(i);
            generateFunction(fn);
            if (i < functions.size() - 1) {
                appendLine();
            }
        }

        indentLevel--;
        appendLine("}");
        return out.toString();
    }

    private void generateFunction(FunctionNode fn) {
        if (fn.isMain()) {
            appendLine("public static void main(String[] args) {");
        } else {
            String returnType = fn.getReturnType().getJavaTypeName();
            StringBuilder params = new StringBuilder();
            for (int i = 0; i < fn.getParameters().size(); i++) {
                String p = fn.getParameters().get(i);
                DataType pType = fn.getParameterTypes().getOrDefault(p, DataType.ANY);
                if (i > 0) params.append(", ");
                params.append(pType.getJavaTypeName()).append(" ").append(p);
            }
            appendLine("public static " + returnType + " " + fn.getName() + "(" + params + ") {");
        }

        indentLevel++;
        generateBlock(fn.getBody());
        indentLevel--;
        appendLine("}");
    }

    private void generateBlock(BlockNode block) {
        for (StatementNode stmt : block.getStatements()) {
            generateStatement(stmt);
        }
    }

    private void generateStatement(StatementNode stmt) {
        if (stmt instanceof AssignmentStatementNode) {
            generateAssignment((AssignmentStatementNode) stmt);
        } else if (stmt instanceof PrintStatementNode) {
            generatePrint((PrintStatementNode) stmt);
        } else if (stmt instanceof IfStatementNode) {
            generateIf((IfStatementNode) stmt);
        } else if (stmt instanceof LoopStatementNode) {
            generateLoop((LoopStatementNode) stmt);
        } else if (stmt instanceof BreakStatementNode) {
            appendLine("break;");
        } else if (stmt instanceof ContinueStatementNode) {
            appendLine("continue;");
        } else if (stmt instanceof ReturnStatementNode) {
            generateReturn((ReturnStatementNode) stmt);
        } else if (stmt instanceof ExpressionStatementNode) {
            appendLine(generateExpression(((ExpressionStatementNode) stmt).getExpression()) + ";");
        }
    }

    private void generateLoop(LoopStatementNode loopStmt) {
        if (loopStmt.isInfinite()) {
            appendLine("while (true) {");
        } else if (loopStmt.hasExposedCounter()) {
            String var = loopStmt.getCounterVariable();
            String count = generateLoopCount(loopStmt.getCountExpression());
            appendLine("for (int " + var + " = 0; " + var + " < " + count + "; " + var + "++) {");
        } else {
            String var = "__loop" + (loopVarCounter++);
            String count = generateLoopCount(loopStmt.getCountExpression());
            appendLine("for (int " + var + " = 0; " + var + " < " + count + "; " + var + "++) {");
        }

        indentLevel++;
        generateBlock(loopStmt.getBody());
        indentLevel--;
        appendLine("}");
    }

    private String generateLoopCount(ExpressionNode expr) {
        String countStr = generateExpression(expr);
        if (expr != null && expr.getEvaluatedType() == DataType.ANY) {
            return "((Number) " + countStr + ").intValue()";
        }
        return countStr;
    }

    private void generateAssignment(AssignmentStatementNode assign) {
        String varName = assign.getVariableName();
        String expr = generateExpression(assign.getValue());

        if (assign.isDeclaration()) {
            String typeName = assign.getVariableType().getJavaTypeName();
            appendLine(typeName + " " + varName + " = " + expr + ";");
        } else {
            String op = assign.getOperator().getRepresentation();
            appendLine(varName + " " + op + " " + expr + ";");
        }
    }

    private void generatePrint(PrintStatementNode printStmt) {
        String expr = generateExpression(printStmt.getExpression());
        appendLine("System.out.println(" + expr + ");");
    }

    private void generateIf(IfStatementNode ifStmt) {
        String condition = generateExpression(ifStmt.getCondition());
        appendLine("if (" + condition + ") {");
        indentLevel++;
        generateBlock(ifStmt.getThenBranch());
        indentLevel--;

        for (IfStatementNode.ElseIfBranch branch : ifStmt.getElseIfBranches()) {
            String elseIfCondition = generateExpression(branch.getCondition());
            appendLine("} else if (" + elseIfCondition + ") {");
            indentLevel++;
            generateBlock(branch.getBody());
            indentLevel--;
        }

        if (ifStmt.getElseBranch() != null) {
            appendLine("} else {");
            indentLevel++;
            generateBlock(ifStmt.getElseBranch());
            indentLevel--;
        }

        appendLine("}");
    }

    private void generateReturn(ReturnStatementNode returnStmt) {
        if (returnStmt.getValue() != null) {
            appendLine("return " + generateExpression(returnStmt.getValue()) + ";");
        } else {
            appendLine("return;");
        }
    }

    private String generateExpression(ExpressionNode expr) {
        if (expr instanceof LiteralExpressionNode) {
            LiteralExpressionNode lit = (LiteralExpressionNode) expr;
            if (lit.getEvaluatedType() == DataType.STRING) {
                return escapeJavaString(lit.getValue().toString());
            }
            return String.valueOf(lit.getValue());
        }

        if (expr instanceof VariableExpressionNode) {
            return ((VariableExpressionNode) expr).getName();
        }

        if (expr instanceof UnaryExpressionNode) {
            UnaryExpressionNode unary = (UnaryExpressionNode) expr;
            String op = unary.getOperator() == TokenType.NOT ? "!" : "-";
            return op + "(" + generateExpression(unary.getOperand()) + ")";
        }

        if (expr instanceof BinaryExpressionNode) {
            BinaryExpressionNode bin = (BinaryExpressionNode) expr;
            String left = generateExpression(bin.getLeft());
            String right = generateExpression(bin.getRight());
            TokenType op = bin.getOperator();

            boolean isStringComp = (bin.getLeft().getEvaluatedType() == DataType.STRING ||
                                    bin.getRight().getEvaluatedType() == DataType.STRING);

            if (op == TokenType.EQUAL) {
                if (isStringComp) {
                    return "Objects.equals(" + left + ", " + right + ")";
                }
                return "(" + left + " == " + right + ")";
            }

            if (op == TokenType.NOT_EQUAL) {
                if (isStringComp) {
                    return "!Objects.equals(" + left + ", " + right + ")";
                }
                return "(" + left + " != " + right + ")";
            }

            if (op == TokenType.AND) {
                return "(" + left + " && " + right + ")";
            }

            if (op == TokenType.OR) {
                return "(" + left + " || " + right + ")";
            }

            return "(" + left + " " + op.getRepresentation() + " " + right + ")";
        }

        if (expr instanceof FunctionCallExpressionNode) {
            FunctionCallExpressionNode call = (FunctionCallExpressionNode) expr;
            StringBuilder sb = new StringBuilder();
            sb.append(call.getFunctionName()).append("(");
            for (int i = 0; i < call.getArguments().size(); i++) {
                if (i > 0) sb.append(", ");
                sb.append(generateExpression(call.getArguments().get(i)));
            }
            sb.append(")");
            return sb.toString();
        }

        return "";
    }

    private String escapeJavaString(String text) {
        StringBuilder sb = new StringBuilder("\"");
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            switch (c) {
                case '"':
                    sb.append("\\\"");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                default:
                    sb.append(c);
                    break;
            }
        }
        sb.append("\"");
        return sb.toString();
    }

    private void appendLine(String line) {
        for (int i = 0; i < indentLevel; i++) {
            out.append("    ");
        }
        out.append(line).append("\n");
    }

    private void appendLine() {
        out.append("\n");
    }
}
