package com.japl.lexer;

import com.japl.common.SourceLocation;

/**
 * Represents a lexical token generated by the Lexer.
 */
public class Token {
    private final TokenType type;
    private final String lexeme;
    private final Object literal;
    private final SourceLocation location;

    public Token(TokenType type, String lexeme, Object literal, SourceLocation location) {
        this.type = type;
        this.lexeme = lexeme;
        this.literal = literal;
        this.location = location;
    }

    public Token(TokenType type, String lexeme, SourceLocation location) {
        this(type, lexeme, null, location);
    }

    public TokenType getType() {
        return type;
    }

    public String getLexeme() {
        return lexeme;
    }

    public Object getLiteral() {
        return literal;
    }

    public SourceLocation getLocation() {
        return location;
    }

    @Override
    public String toString() {
        if (literal != null) {
            return String.format("%s ('%s', %s) at %s", type, lexeme, literal, location);
        }
        return String.format("%s ('%s') at %s", type, lexeme, location);
    }
}
